### ISSUE TITLE
add support vscode 

### ISSUE THREAD

**Issue by kyakubi** [ui5experts/ui5-schemas#1]
👍

**Comment by cschuff** [comment]
Hi,

as long as this is still an [open issue at Microsoft](https://github.com/Microsoft/vscode/issues/1440) I don't see how to implement this...
Anyways maybe this helps: https://marketplace.visualstudio.com/items?itemName=apazureck.ui5-ts

BR
Chris

**Comment by angelozerr** [comment]
@cschuff have you tried https://github.com/redhat-developer/vscode-xml which uses Xerces to validate XML based on XML Schema ?
