### ISSUE TITLE
Bound aggregation attributes

### ISSUE THREAD

**Issue by JarkkoPeltonen** [ui5experts/ui5-schemas#4]
Aggregations are not allowed as attributes. Example:
![image](https://user-images.githubusercontent.com/19328835/29505793-fcf3aa2c-8650-11e7-8b9c-4a632454430e.png)

Can we have all aggregations of element as allowed attributes?

**Comment by cschuff** [comment]
Hi,

this is a known limitation of the xml schemas provided by SAP. So this could be a feature request for OpenUI5 itself.

Anyways, I was already looking into these kinds of issues and have some ideas for future versions.

BR
Chris
