### ISSUE TITLE
ui5-schemas error [enhance] Error: Unexpected close tag

### ISSUE THREAD

**Issue by pubmikeb** [ui5experts/ui5-schemas#47]
I installed ui5-schemas with `npm install -g ui5-schemas`
Then I try to execute `ui5-schemas --sdk openui5nightly` and get the following error:

> ui5-schemas info Attempting to download latest version of 'openui5nightly'. Determining latest version...
> ui5-schemas info https://openui5nightly.hana.ondemand.com/resources/sap-ui-version.json
> ui5-schemas info Detected version of sdk 'openui5nightly' is '1.74.0-SNAPSHOT'
> ui5-schemas info Preparing 'openui5nightly' schemas in version '1.74.0-SNAPSHOT'...
> ui5-schemas info Yay, all schema files were successfully downloaded!
> ui5-schemas info [enhance] Making schemas even cooler...
> ui5-schemas error [enhance] Error: Unexpected close tag
> Line: 46
> Column: 8
> Char: >
>     at error (C:\Program Files\nodejs\node_modules\ui5-schemas\node_modules\sax\lib\sax.js:651:10)
>     at strictFail (C:\Program Files\nodejs\node_modules\ui5-schemas\node_modules\sax\lib\sax.js:677:7)
>     at closeTag (C:\Program Files\nodejs\node_modules\ui5-schemas\node_modules\sax\lib\sax.js:871:9)
>     at SAXParser.write (C:\Program Files\nodejs\node_modules\ui5-schemas\node_modules\sax\lib\sax.js:1436:13)
>     at Parser.exports.Parser.Parser.parseString (C:\Program Files\nodejs\node_modules\ui5-schemas\node_modules\xml2js\lib\parser.js:322:31)
>     at Parser.parseString (C:\Program Files\nodejs\node_modules\ui5-schemas\node_modules\xml2js\lib\parser.js:5:59)
>     at C:\Program Files\nodejs\node_modules\ui5-schemas\lib\upgrade.js:103:14

When executing `ui5-schemas --sdk openui5` in Node.js console everything is OK.

When I execute `ui5-schemas --sdk openui5` withing IDEA 2019.3, I get an error:
> C:\Users\User\IdeaProjects\%PROJ%>ui5-schemas --sdk openui5
> ui5-schemas info Attempting to download latest version of 'openui5'. Determining latest version...
> ui5-schemas info https://openui5.hana.ondemand.com/resources/sap-ui-version.json
> ui5-schemas info Detected version of sdk 'openui5' is '1.72.1'
> ui5-schemas info Preparing 'openui5' schemas in version '1.72.1'...
> ui5-schemas info Yay, all schema files were successfully downloaded!
> ui5-schemas info [enhance] Making schemas even cooler...
> ui5-schemas info [link] Discovered an .idea project! Registering schemas...
> ui5-schemas error TypeError: Cannot read property 'filter' of undefined
>     at C:\Users\User\IdeaProjects\%PROJ%\node_modules\ui5-schemas\lib\link.js:63:44
>     at Parser.<anonymous> (C:\Users\User\IdeaProjects\%PROJ%\node_modules\xml2js\lib\parser.js:303:18)
>     at Parser.emit (events.js:223:5)
>     at SAXParser.onclosetag (C:\Users\User\IdeaProjects\%PROJ%\node_modules\xml2js\lib\parser.js:261:26)
>     at emit (C:\Users\User\IdeaProjects\%PROJ%\node_modules\sax\lib\sax.js:624:35)
>     at emitNode (C:\Users\User\IdeaProjects\%PROJ%\node_modules\sax\lib\sax.js:629:5)
>     at closeTag (C:\Users\User\IdeaProjects\%PROJ%\node_modules\sax\lib\sax.js:889:7)
>     at SAXParser.write (C:\Users\User\IdeaProjects\%PROJ%\node_modules\sax\lib\sax.js:1436:13)
>     at Parser.exports.Parser.Parser.parseString (C:\Users\User\IdeaProjects\%PROJ%\node_modules\xml2js\lib\parser.js:322:31)
>     at Parser.parseString (C:\Users\User\IdeaProjects\%PROJ%\node_modules\xml2js\lib\parser.js:5:59)
>     at registerLibs (C:\Users\User\IdeaProjects\%PROJ%\node_modules\ui5-schemas\lib\link.js:33:12)
>     at C:\Users\User\IdeaProjects\%PROJ%\node_modules\ui5-schemas\lib\link.js:98:11
> ui5-schemas info [enhance] Enhancing done!

**Comment by cschuff** [comment]
Hi Mike,

as @petermuessig pointed out in the related @openui5 issue there will likely be no fix for this. I'm in touch with @petermuessig to evaluate options on how to keep this project alive. 

It will probably result in a new project. Due to my limited resources don't expect too much before March '20. 

Until then as peter mentioned stick with the latest available schemas of the 1.71 ui5 release.

BR
Chris
